title: Hi there
author: Mou Tong
email: moutong945@163.com
description: > # this means to ignore newlines until "baseurl:"
  I'm testing Github Pages here!

theme: minima

# social links
twitter_username: anonymous # DO NOT include the @ character, or else the build will fail!
github_username:  mtyuio # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
